server:
  port: 8022
spring:
  application:
    name: clients-manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  profiles:
    active: dev
  cloud:
    config:
      label: master
  config:
    import: optional:configserver:http://localhost:8021